package views;

import config.Conectar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author maria
 */
public class telaLogin extends javax.swing.JFrame {

    /**
     * Creates new form telaInicial
     */
    
    Conectar cs = new Conectar();
    public telaLogin() {
        this.con = new Conectar();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelLogin = new javax.swing.JPanel();
        txtUsuario = new app.bolivia.swing.JCTextField();
        txtSenha = new jpass.JRPasswordField();
        btnLogin = new javax.swing.JButton();
        btnRessetSenha = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        telaInicial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Abraão Lemos LTDA");
        setLocationByPlatform(true);
        setResizable(false);
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        getContentPane().setLayout(flowLayout1);

        painelLogin.setAutoscrolls(true);
        painelLogin.setMaximumSize(new java.awt.Dimension(0, 0));
        painelLogin.setMinimumSize(new java.awt.Dimension(0, 0));
        painelLogin.setPreferredSize(new java.awt.Dimension(1390, 900));
        painelLogin.setRequestFocusEnabled(false);
        painelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setBackground(java.awt.SystemColor.controlHighlight);
        txtUsuario.setBorder(null);
        txtUsuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtUsuario.setOpaque(false);
        txtUsuario.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyReleased(evt);
            }
        });
        painelLogin.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, 310, -1));

        txtSenha.setBackground(java.awt.SystemColor.controlHighlight);
        txtSenha.setBorder(null);
        txtSenha.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtSenha.setName(""); // NOI18N
        txtSenha.setOpaque(false);
        txtSenha.setPhColor(new java.awt.Color(255, 255, 255));
        painelLogin.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, 310, -1));

        btnLogin.setContentAreaFilled(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        painelLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 540, 140, 30));

        btnRessetSenha.setContentAreaFilled(false);
        btnRessetSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRessetSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRessetSenhaActionPerformed(evt);
            }
        });
        painelLogin.add(btnRessetSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 690, 160, 20));

        jPanel1.setBackground(new java.awt.Color(48, 105, 139));
        painelLogin.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 220, 50));

        telaInicial.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        telaInicial.setForeground(java.awt.Color.white);
        telaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Tela Login.png"))); // NOI18N
        telaInicial.setToolTipText("");
        telaInicial.setMaximumSize(new java.awt.Dimension(0, 0));
        telaInicial.setMinimumSize(new java.awt.Dimension(0, 0));
        telaInicial.setName(""); // NOI18N
        telaInicial.setVerifyInputWhenFocusTarget(false);
        painelLogin.add(telaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1450, 873));

        getContentPane().add(painelLogin);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void txtUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyReleased
       txtUsuario.setText(txtUsuario.getText().toLowerCase());
    }//GEN-LAST:event_txtUsuarioKeyReleased

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String user = txtUsuario.getText();        
        String password = txtSenha.getText();
        
        //Compara se está vazio o campo usuario e senha
        if(user.equals("") || password.equals("")){
            //Retorna uma tela com a mensagem de erro
            JOptionPane.showMessageDialog(this, "Preencha os Campos", "Login", 0,
                    new ImageIcon(getClass().getResource("/Imagem/info.png")));
            
        }else{
            //chama o método que faz o login
           Logar(user, password);
            try {
                cs.conexao().close();
            } catch (SQLException ex) {
            }
        }               
    }//GEN-LAST:event_btnLoginActionPerformed

    
    //Criando a conexão com o banco
    Conectar con = new Conectar();
    Connection cn = con.conexao();
    
    public void Logar(String id , String senha){
        String dado = null;
        
            try {
            //seleciona o email quando for igual ao valor passado baseado no id 
            String sql = "SELECT email FROM usuario WHERE email = '" + id + "' ";            
            //Inicialização do banco de dados atravez do ResultSet
            Statement st = cn.createStatement();
            //Ele que executa a consulta no java
            ResultSet rs = st.executeQuery(sql);
            
            if(rs.first()){
                //seleciona a senha do usuario
                String sql1 = "SELECT senha FROM usuario WHERE senha = '" + senha + "' ";
                System.out.println("Senha" + sql1);
                //Toda a consulta gera esses dois Statement e ResultSet, não esquecer de sempre colocar um nome diferente da anterior
                Statement st1 = cn.createStatement();
                ResultSet rs1 = st1.executeQuery(sql1);
                
                if(rs1.next()){                    
                    //Fecha a janela atual(Login)
                    dispose();
                    //Chama a tela de Menu
                    telaInicial menu = new telaInicial();
                    menu.setLocationRelativeTo(null);
                    menu.setVisible(true);
     
                }else{
                     JOptionPane.showMessageDialog(this, "Senha Incorreta!", "Login", 0,
                    new ImageIcon(getClass().getResource("/Imagem/info.png")));
                }
                
            }else{
                JOptionPane.showMessageDialog(this, "O usuário não existe no banco de dados!", "Login", 0,
                    new ImageIcon(getClass().getResource("/Imagem/info.png")));
            }
                      
        } catch (Exception e) {
        }
    
    }    
    
    private void btnRessetSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRessetSenhaActionPerformed
          
    }//GEN-LAST:event_btnRessetSenhaActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                telaLogin tela = new telaLogin();
                tela.setLocationRelativeTo(null);
                tela.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRessetSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel painelLogin;
    private javax.swing.JLabel telaInicial;
    private jpass.JRPasswordField txtSenha;
    private app.bolivia.swing.JCTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
