package views;

import config.Usuarios;
import config.UsuariosDao;
import javax.swing.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author mariana
 */
public class telaCadastroUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form telaCadastroUsuario
     */
    Usuarios usuarios = new Usuarios();

    public telaCadastroUsuario() {
        initComponents();
        popularJComboBoxFuncao();

        /*ImageIcon icon = new ImageIcon("src/Imagem/Tela Cadastro Usuário.png");
        icon.setImage(icon.getImage().getScaledInstance(telaCadastroUsuario.getWidth(),telaCadastroUsuario.getHeight(), 1));
        telaCadastroUsuario.setIcon(icon);*/
 /*setLayout(new GridLayout());
        tela = new FundoTela("Imagem/Tela Cadastro Usuário.png");
        getContentPane().add(tela);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtNome = new app.bolivia.swing.JCTextField();
        txtReCadastro = new app.bolivia.swing.JCTextField();
        txtEndereco = new app.bolivia.swing.JCTextField();
        txtNumero = new app.bolivia.swing.JCTextField();
        txtBairro = new app.bolivia.swing.JCTextField();
        txtCidade = new app.bolivia.swing.JCTextField();
        txtEstado = new app.bolivia.swing.JCTextField();
        txtCEP = new app.bolivia.swing.JCTextField();
        txtTelefone = new app.bolivia.swing.JCTextField();
        txtEmail = new app.bolivia.swing.JCTextField();
        txtCpf = new app.bolivia.swing.JCTextField();
        txtSenha = new jpass.JRPasswordField();
        txtReConsulta = new app.bolivia.swing.JCTextField();
        btnConsultarRE = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCBoxFuncao = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lblGerenciarUsuario = new javax.swing.JLabel();
        telaCadastroUsuario = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        setTitle("Abraão Lemos LTDA");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(10, 10));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNome.setBorder(null);
        txtNome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtNome.setOpaque(false);
        txtNome.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });
        jPanel2.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 580, 30));

        txtReCadastro.setBorder(null);
        txtReCadastro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtReCadastro.setOpaque(false);
        txtReCadastro.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtReCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtReCadastroKeyReleased(evt);
            }
        });
        jPanel2.add(txtReCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 320, 160, 30));

        txtEndereco.setBorder(null);
        txtEndereco.setText(" ");
        txtEndereco.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtEndereco.setOpaque(false);
        txtEndereco.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        txtEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEnderecoKeyReleased(evt);
            }
        });
        jPanel2.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 510, 30));

        txtNumero.setBorder(null);
        txtNumero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtNumero.setOpaque(false);
        txtNumero.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroKeyReleased(evt);
            }
        });
        jPanel2.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 390, 70, 30));

        txtBairro.setBorder(null);
        txtBairro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtBairro.setOpaque(false);
        txtBairro.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBairroKeyReleased(evt);
            }
        });
        jPanel2.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 390, 130, 30));

        txtCidade.setBorder(null);
        txtCidade.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtCidade.setOpaque(false);
        txtCidade.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCidadeKeyReleased(evt);
            }
        });
        jPanel2.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 230, 30));

        txtEstado.setBorder(null);
        txtEstado.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtEstado.setOpaque(false);
        txtEstado.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEstadoKeyReleased(evt);
            }
        });
        jPanel2.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 470, 100, 30));

        txtCEP.setBorder(null);
        txtCEP.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtCEP.setOpaque(false);
        txtCEP.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCEPKeyReleased(evt);
            }
        });
        jPanel2.add(txtCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 470, 130, 30));

        txtTelefone.setBorder(null);
        txtTelefone.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtTelefone.setOpaque(false);
        txtTelefone.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefoneKeyReleased(evt);
            }
        });
        jPanel2.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 470, 220, -1));

        txtEmail.setBorder(null);
        txtEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtEmail.setOpaque(false);
        txtEmail.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, 460, -1));

        txtCpf.setBorder(null);
        txtCpf.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtCpf.setOpaque(false);
        txtCpf.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCpfKeyReleased(evt);
            }
        });
        jPanel2.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 540, 300, -1));

        txtSenha.setBorder(null);
        txtSenha.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtSenha.setName(""); // NOI18N
        txtSenha.setOpaque(false);
        txtSenha.setPhColor(new java.awt.Color(255, 255, 255));
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        jPanel2.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 610, 290, 30));

        txtReConsulta.setBorder(null);
        txtReConsulta.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtReConsulta.setOpaque(false);
        txtReConsulta.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtReConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtReConsultaKeyReleased(evt);
            }
        });
        jPanel2.add(txtReConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 170, 20));

        btnConsultarRE.setContentAreaFilled(false);
        btnConsultarRE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultarRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarREActionPerformed(evt);
            }
        });
        jPanel2.add(btnConsultarRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 30, 40));

        btnLimpar.setContentAreaFilled(false);
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 680, 40, 40));

        btnAlterar.setContentAreaFilled(false);
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 680, -1, 40));

        btnSalvar.setContentAreaFilled(false);
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 680, 40, 40));
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 690, -1, -1));

        jCBoxFuncao.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jCBoxFuncao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCBoxFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBoxFuncaoActionPerformed(evt);
            }
        });
        jPanel2.add(jCBoxFuncao, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 610, 480, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblGerenciarUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblGerenciarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGerenciarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblGerenciarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 750, 810, 60));

        telaCadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Tela Cadastro Usuário.png"))); // NOI18N
        telaCadastroUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(telaCadastroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 900));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void limparCampos() {
        txtNome.setText("");
        txtCpf.setText("");
        txtEmail.setText("");
        txtEndereco.setText("");
        txtNumero.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtEstado.setText("");
        txtCEP.setText("");
        txtReCadastro.setText("");
        txtReConsulta.setText("");
        txtTelefone.setText("");
        txtSenha.setText("");
        jCheckBox1.setSelected(false);

    }

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased
        //usuario.setText(usuario.getText().toUpperCase());
    }//GEN-LAST:event_txtNomeKeyReleased

    private void txtEnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnderecoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoKeyReleased

    private void txtReCadastroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReCadastroKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReCadastroKeyReleased

    private void txtTelefoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtCpfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfKeyReleased

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void txtReConsultaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReConsultaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReConsultaKeyReleased

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        UsuariosDao dao = new UsuariosDao();
        boolean status;
        int resp;
        if (txtReCadastro.getText().isEmpty() || txtNome.getText().isEmpty() || txtEndereco.getText().isEmpty() || txtNumero.getText().isEmpty()
                || txtBairro.getText().isEmpty() || txtCidade.getText().isEmpty() || txtEstado.getText().isEmpty() || txtCEP.getText().isEmpty()
                || txtEmail.getText().isEmpty() || txtTelefone.getText().isEmpty() || txtCpf.getText().isEmpty() || txtSenha.getText().isEmpty()) {

            lblGerenciarUsuario.setText("Todos os campos de cadastro devem ser preenchidos.");
        } else {

            usuarios.setRe(txtReCadastro.getText());
            usuarios.setNome(txtNome.getText());
            usuarios.setEndereco(txtEndereco.getText());
            usuarios.setNumero(Integer.parseInt(txtNumero.getText()));
            usuarios.setBairro(txtBairro.getText());
            usuarios.setCidade(txtCidade.getText());
            usuarios.setEstado(txtEstado.getText());
            usuarios.setCep(txtCEP.getText());
            usuarios.setFuncao(jCBoxFuncao.getSelectedItem().toString());
            usuarios.setEmail(txtEmail.getText());
            usuarios.setTelefone(txtTelefone.getText());
            usuarios.setCpf(txtCpf.getText());
            usuarios.setSenha(txtSenha.getText());
            usuarios.setInativarUsuario(jCheckBox1.isSelected());

            status = dao.conectar();
            if (!status) {
                lblGerenciarUsuario.setText("Erro na conexão com Banco do Dados.");
            } else {
                resp = dao.salvar(usuarios);
                if (resp == 1) {
                    lblGerenciarUsuario.setText("Dados inseridos com sucesso!");
                    limparCampos();
                    txtNome.requestFocus();
                } else if (resp == 1062) {
                    txtReConsulta.setText("");
                    txtReCadastro.requestFocus();
                    lblGerenciarUsuario.setText("Numero do RE já cadastrado.");

                } else {
                    lblGerenciarUsuario.setText("Erro ao salvar!");

                }

                dao.desconectar();
            }
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed

    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void btnConsultarREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarREActionPerformed

        String reConsulta;
        if (txtReConsulta.getText().isEmpty()) {
            lblGerenciarUsuario.setText("RE de consulta deve ser preenchido.");
        } else {
            reConsulta = txtReConsulta.getText();
            UsuariosDao dao = new UsuariosDao();
            boolean status = dao.conectar();
            if (status == true) {
                usuarios = dao.consultar(reConsulta);
                System.out.println(" " + reConsulta);
                if (usuarios == null) {
                    lblGerenciarUsuario.setText("Funcionario não encontrado.");
                } else {
                    txtReConsulta.setText("");
                    txtReCadastro.setText(usuarios.getRe());
                    txtNome.setText(usuarios.getNome());
                    txtEndereco.setText(usuarios.getEndereco());
                    txtEmail.setText(usuarios.getEmail());
                    txtTelefone.setText(usuarios.getTelefone());
                    txtCpf.setText(usuarios.getCpf());
                    txtSenha.setText(usuarios.getSenha());
                    jCheckBox1.setSelected(usuarios.getInativarUsuario());
                    txtNumero.setText(usuarios.getNumero().toString());
                    txtBairro.setText(usuarios.getBairro());
                    txtCidade.setText(usuarios.getCidade());
                    txtEstado.setText(usuarios.getEstado());
                    txtCEP.setText(usuarios.getCep());
                    jCBoxFuncao.setSelectedItem(usuarios.getFuncao());

                    lblGerenciarUsuario.setText("");
                    usuarios.setEstado(txtEstado.getText());
                    usuarios.setCep(txtCEP.getText());
                    usuarios.setFuncao(jCBoxFuncao.getSelectedItem().toString());

                }
            } else {
                lblGerenciarUsuario.setText("Erro na conexão do banco de Dados.");
            }

            dao.desconectar();
        }
    }//GEN-LAST:event_btnConsultarREActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        UsuariosDao dao = new UsuariosDao();
        if (txtReCadastro.getText().isEmpty() || txtNome.getText().isEmpty() || txtEndereco.getText().isEmpty() || txtNumero.getText().isEmpty()
                || txtBairro.getText().isEmpty() || txtCidade.getText().isEmpty() || txtEstado.getText().isEmpty() || txtCEP.getText().isEmpty()
                || txtEmail.getText().isEmpty() || txtTelefone.getText().isEmpty() || txtCpf.getText().isEmpty() || txtSenha.getText().isEmpty()) {

            lblGerenciarUsuario.setText("Todos os campos de cadastro devem ser preenchidos.");
        } else {

            usuarios.setRe(txtReCadastro.getText());
            usuarios.setNome(txtNome.getText());
            usuarios.setEndereco(txtEndereco.getText());
            usuarios.setEmail(txtEmail.getText());
            usuarios.setTelefone(txtTelefone.getText());
            usuarios.setCpf(txtCpf.getText());
            usuarios.setSenha(txtSenha.getText());
            usuarios.setInativarUsuario(jCheckBox1.isSelected());
            usuarios.setNumero(Integer.parseInt(txtNumero.getText()));
            usuarios.setBairro(txtBairro.getText());
            usuarios.setCidade(txtCidade.getText());
            usuarios.setEstado(txtEstado.getText());
            usuarios.setCep(txtCEP.getText());
            usuarios.setFuncao(jCBoxFuncao.getSelectedItem().toString());

            boolean status = dao.conectar();
            if (status) {
                status = dao.alterar(usuarios);
                if (status) {
                    lblGerenciarUsuario.setText("Usuario Alterado com sucesso.");
                    limparCampos();

                } else {
                    lblGerenciarUsuario.setText("Usuário não foi alterado.");
                }
                dao.desconectar();
            } else {
                lblGerenciarUsuario.setText("Erro na conexão com o Banco de Dados.");
            }

            dao.desconectar();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
        lblGerenciarUsuario.setText("");


    }//GEN-LAST:event_btnLimparActionPerformed

    public void popularJComboBoxFuncao() {

        String[] funcao = {"Administrador", "Colaborador"};
        for (String nome : funcao) {
            jCBoxFuncao.addItem(nome);
        }
    }

    private void jCBoxFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBoxFuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBoxFuncaoActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroKeyReleased

    private void txtBairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroKeyReleased

    private void txtCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCidadeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeKeyReleased

    private void txtEstadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoKeyReleased

    private void txtCEPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCEPKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCEPKeyReleased

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        /*ImageIcon icon = new ImageIcon("src/Imagem/Tela Cadastro Usuário.png");
        icon.setImage(icon.getImage().getScaledInstance(telaCadastroUsuario.getWidth(),telaCadastroUsuario.getHeight(), 1));
        telaCadastroUsuario.setIcon(icon);*/
    }//GEN-LAST:event_formInternalFrameOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultarRE;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> jCBoxFuncao;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblGerenciarUsuario;
    private javax.swing.JLabel telaCadastroUsuario;
    private app.bolivia.swing.JCTextField txtBairro;
    private app.bolivia.swing.JCTextField txtCEP;
    private app.bolivia.swing.JCTextField txtCidade;
    private app.bolivia.swing.JCTextField txtCpf;
    private app.bolivia.swing.JCTextField txtEmail;
    private app.bolivia.swing.JCTextField txtEndereco;
    private app.bolivia.swing.JCTextField txtEstado;
    private app.bolivia.swing.JCTextField txtNome;
    private app.bolivia.swing.JCTextField txtNumero;
    private app.bolivia.swing.JCTextField txtReCadastro;
    private app.bolivia.swing.JCTextField txtReConsulta;
    private jpass.JRPasswordField txtSenha;
    private app.bolivia.swing.JCTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
