/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author maria
 */
public class telaInicial extends javax.swing.JFrame {

    /**
     * Creates new form telaInicial
     */
    public telaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGerenciarItens = new javax.swing.JButton();
        btnGerenciarVeiculo = new javax.swing.JButton();
        btnControleManutencao = new javax.swing.JButton();
        btnAgendamento = new javax.swing.JButton();
        btnCadastrarUsuario = new javax.swing.JButton();
        telaInicial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1440, 900));
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 900));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGerenciarItens.setContentAreaFilled(false);
        btnGerenciarItens.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnGerenciarItens, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 630, 340, 140));

        btnGerenciarVeiculo.setContentAreaFilled(false);
        btnGerenciarVeiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnGerenciarVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 630, 340, 140));

        btnControleManutencao.setContentAreaFilled(false);
        btnControleManutencao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnControleManutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 630, 340, 140));

        btnAgendamento.setContentAreaFilled(false);
        btnAgendamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 60, 160, 30));

        btnCadastrarUsuario.setContentAreaFilled(false);
        btnCadastrarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnCadastrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 220, 30));

        telaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Tela Inicial.png"))); // NOI18N
        jPanel1.add(telaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendamento;
    private javax.swing.JButton btnCadastrarUsuario;
    private javax.swing.JButton btnControleManutencao;
    private javax.swing.JButton btnGerenciarItens;
    private javax.swing.JButton btnGerenciarVeiculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel telaInicial;
    // End of variables declaration//GEN-END:variables
}
