package views;

import config.Conexao;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author maria
 */
public class telaLogin extends javax.swing.JFrame {

    /**
     * Creates new form telaInicial
     */
    public telaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelLogin = new javax.swing.JPanel();
        usuario = new app.bolivia.swing.JCTextField();
        senha = new jpass.JRPasswordField();
        btnLogin = new javax.swing.JButton();
        cadastroUsuario = new javax.swing.JButton();
        telaInicial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Abraão Lemos LTDA");
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        painelLogin.setPreferredSize(new java.awt.Dimension(1600, 1000));
        painelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuario.setBackground(new java.awt.Color(34, 102, 145));
        usuario.setBorder(null);
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usuario.setOpaque(false);
        usuario.setPhColor(new java.awt.Color(255, 255, 255));
        usuario.setPlaceholder("USUARIO");
        usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usuarioKeyReleased(evt);
            }
        });
        painelLogin.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 420, 350, -1));

        senha.setBackground(new java.awt.Color(34, 102, 145));
        senha.setBorder(null);
        senha.setForeground(new java.awt.Color(255, 255, 255));
        senha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        senha.setName(""); // NOI18N
        senha.setOpaque(false);
        senha.setPhColor(new java.awt.Color(255, 255, 255));
        senha.setPlaceholder("SENHA");
        senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaActionPerformed(evt);
            }
        });
        painelLogin.add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 518, 350, -1));

        btnLogin.setToolTipText("");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        painelLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 625, 160, 30));
        painelLogin.add(cadastroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 220, 30));

        telaInicial.setToolTipText("");
        telaInicial.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        painelLogin.add(telaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, -30, 1561, -1));

        getContentPane().add(painelLogin);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioKeyReleased
        usuario.setText(usuario.getText().toUpperCase());
    }//GEN-LAST:event_usuarioKeyReleased

    private void senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        String user = usuario.getText();        
        String password = senha.getText();
        
        //Compara se está vazio o campo usuario e senha
        if(user.equals("") || password.equals("")){
            //Retorna uma tela com a mensagem de erro
            JOptionPane.showMessageDialog(this, "Preencha os Campos", "Login", 0,
                    new ImageIcon(getClass().getResource("/imagens/info.png")));
            
        }else{
            //chama o método que faz o login
           Logar(user, password);
        } 
    }//GEN-LAST:event_btnLoginActionPerformed

        //Criando a conexão com o banco
    Conexao con = new Conexao();
    Connection cn = con.conexao();
    
    public void Logar(String id , String senha){
        String dado = null;
        
            try {
            //seleciona o email quando for igual ao valor passado baseado no id 
            String sql = "SELECT email FROM usuario WHERE email = '" + id + "' ";            
            //Inicialização do banco de dados atravez do ResultSet
            Statement st = cn.createStatement();
            //Ele que executa a consulta no java
            ResultSet rs = st.executeQuery(sql);
            
            if(rs.first()){
                //seleciona a senha do usuario
                String sql1 = "SELECT senha FROM usuario WHERE senha = '" + senha + "' ";
                //Toda a consulta gera esses dois Statement e ResultSet, não esquecer de sempre colocar um nome diferente da anterior
                Statement st1 = cn.createStatement();
                ResultSet rs1 = st1.executeQuery(sql1);
                
                if(rs1.first()){
                    /*//Define o tipo de Usuario, Adm ou padrão
                    String sql2 = "SELECT tipo_us FROM usuario WHERE email = '" + id + "' "
                            + "and senha = '" + senha + "' ";
                    Statement st2 = cn.createStatement();
                    ResultSet rs2 = st2.executeQuery(sql2);*/
                    
                    //Enquanto ele encontrar os dados de cima ele vai retornar a query de cima
                    /*while(rs2.next()){
                        dado = rs2.getString(1);
                        
                    }*/
                    
                    //Fecha a janela atual(Login)
                    dispose();
                    //Chama a tela de Menu
                    //MenuPrincipal menu = new MenuPrincipal();
                    JOptionPane.showMessageDialog(this, "Bem vindo ao Sistema " + dado, "Usuario", 0,
                        new ImageIcon(getClass().getResource("/imagens/info.png")));                    
                    
                    //Caso o perfil seja Administrador
                    /*if (dado.equals("ADM")){
                        String sql3 = "SELECT email FROM usuario WHERE email = '" + id + "' ";
                        Statement st3 = cn.createStatement();
                        ResultSet rs3 = st3.executeQuery(sql3);
                        
                        //Aqui é como se estivesse buscando novos resultados
                        while(rs3.next()){
                            dado = rs3.getString(1);                            
                        }
                        
                        //Fecha a janela atual(Login)
                        dispose();
                        //Chama a tela de Menu
                        MenuPrincipal menu = new MenuPrincipal();
                        JOptionPane.showMessageDialog(this, "Bem vindo ao Sistema " + dado, "Administrador", 0,
                            new ImageIcon(getClass().getResource("/imagens/info.png")));
                        
                        //Na tela de menu principal tem que ter o usuario tipo label* aula 21-login no sistema
                        /*menu.userConect.setText(dado);
                        menu.setLocationRelativeTo(null);
                        menu.setVisible(true);
                          
                    }
                    //Acredito que essa parte não serve porque chamaria uma tela diferente no caso de usuario padrão
                    else{
                        String sql4 = "SELECT nome_us FROM usuarios WHERE nome_us = '" + id + "' ";
                        Statement st4 = cn.createStatement();
                        ResultSet rs4 = st4.executeQuery(sql4);
                        
                        while(rs4.next()){
                            dado = rs4.getString(1);                            
                        }
                         
                        dispose();
                        //Definir um Menu diferente para usuario normal
                        
                        /*MenuPrincipalP menuP = new MenuPrincipalP();
                        JOptionPane.showMessageDialog(this, "Bem vindo ao Sistema " + dado, "Usuário Padrão", 0,
                            new ImageIcon(getClass().getResource("/imagens/info.png")));
                          
                        menuP.userConect.setText(dado);
                        menuP.setLocationRelativeTo(null);
                        menuP.setVisible(true);*/
                          
                    
                    
                    
                }else{
                     JOptionPane.showMessageDialog(this, "Senha Incorreta!", "Login", 0,
                    new ImageIcon(getClass().getResource("/imagens/info.png")));
                }
                
            }else{
                JOptionPane.showMessageDialog(this, "O usuário não existe no banco de dados!", "Login", 0,
                    new ImageIcon(getClass().getResource("/imagens/info.png")));
            }
                      
        } catch (Exception e) {
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */                                                

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                telaLogin tela = new telaLogin();
                tela.setLocationRelativeTo(null);
                tela.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton cadastroUsuario;
    private javax.swing.JPanel painelLogin;
    private jpass.JRPasswordField senha;
    private javax.swing.JLabel telaInicial;
    private app.bolivia.swing.JCTextField usuario;
    // End of variables declaration//GEN-END:variables
}
