/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author maria
 */
public class telaManutencao extends javax.swing.JFrame {

    /**
     * Creates new form telaManutencao
     */
    public telaManutencao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPlacaManut = new app.bolivia.swing.JCTextField();
        btnConsultarPlaca = new javax.swing.JButton();
        btnLimparPlaca = new javax.swing.JButton();
        pnlConsultarOSManut = new javax.swing.JPanel();
        lblConsultarOSManut = new javax.swing.JLabel();
        cboCodOSPreventManut = new javax.swing.JComboBox<>();
        cboCodOSCorretManut = new javax.swing.JComboBox<>();
        btnConsultarOSManut = new javax.swing.JButton();
        btnLimparOSManut = new javax.swing.JButton();
        pnlConsultarOSPrevCorret = new javax.swing.JPanel();
        lblConsultarOSPrevCorret = new javax.swing.JLabel();
        scpnlOSPrevent = new javax.swing.JScrollPane();
        tblConsOSPrevent = new javax.swing.JTable();
        scpnlOSCorret = new javax.swing.JScrollPane();
        tblConsOSCorret = new javax.swing.JTable();
        txtCodOSCorretAdd = new app.bolivia.swing.JCTextField();
        txtCodProd = new app.bolivia.swing.JCTextField();
        btnAdicionarProd = new javax.swing.JButton();
        btnExcluirProd = new javax.swing.JButton();
        txtCodOSPrevFin = new app.bolivia.swing.JCTextField();
        txtCodOSCorretFin = new app.bolivia.swing.JCTextField();
        txtValorTotPrev = new app.bolivia.swing.JCTextField();
        txtValorTotCorret = new app.bolivia.swing.JCTextField();
        btnSalvarOSFin = new javax.swing.JButton();
        btnLimparOSFin = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        rdbtn5Prev = new javax.swing.JRadioButton();
        rdbtn10Prev = new javax.swing.JRadioButton();
        rdbtn20Prev = new javax.swing.JRadioButton();
        rdbtn5Corret = new javax.swing.JRadioButton();
        rdbtn10Corret = new javax.swing.JRadioButton();
        rdbtn20Corret = new javax.swing.JRadioButton();
        pnlAdicionarProd = new javax.swing.JPanel();
        lblAdicionarProd = new javax.swing.JLabel();
        pnlFinalizarOS = new javax.swing.JPanel();
        lblFinalizarOS = new javax.swing.JLabel();
        telaManutencao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPlacaManut.setBorder(null);
        txtPlacaManut.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtPlacaManut.setOpaque(false);
        txtPlacaManut.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtPlacaManut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlacaManutKeyReleased(evt);
            }
        });
        jPanel1.add(txtPlacaManut, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 160, 20));

        btnConsultarPlaca.setContentAreaFilled(false);
        btnConsultarPlaca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnConsultarPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 30, 40));

        btnLimparPlaca.setContentAreaFilled(false);
        btnLimparPlaca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnLimparPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 40, 30));

        pnlConsultarOSManut.setBackground(new java.awt.Color(204, 204, 204));
        pnlConsultarOSManut.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlConsultarOSManutLayout = new javax.swing.GroupLayout(pnlConsultarOSManut);
        pnlConsultarOSManut.setLayout(pnlConsultarOSManutLayout);
        pnlConsultarOSManutLayout.setHorizontalGroup(
            pnlConsultarOSManutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        pnlConsultarOSManutLayout.setVerticalGroup(
            pnlConsultarOSManutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel1.add(pnlConsultarOSManut, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 620, 40));

        lblConsultarOSManut.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel1.add(lblConsultarOSManut, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 600, 30));

        jPanel1.add(cboCodOSPreventManut, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 180, 40));

        jPanel1.add(cboCodOSCorretManut, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 180, 40));

        btnConsultarOSManut.setContentAreaFilled(false);
        btnConsultarOSManut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnConsultarOSManut, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 30, 30));

        btnLimparOSManut.setContentAreaFilled(false);
        btnLimparOSManut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnLimparOSManut, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 30, 30));

        pnlConsultarOSPrevCorret.setBackground(new java.awt.Color(204, 204, 204));
        pnlConsultarOSPrevCorret.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlConsultarOSPrevCorretLayout = new javax.swing.GroupLayout(pnlConsultarOSPrevCorret);
        pnlConsultarOSPrevCorret.setLayout(pnlConsultarOSPrevCorretLayout);
        pnlConsultarOSPrevCorretLayout.setHorizontalGroup(
            pnlConsultarOSPrevCorretLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        pnlConsultarOSPrevCorretLayout.setVerticalGroup(
            pnlConsultarOSPrevCorretLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel1.add(pnlConsultarOSPrevCorret, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 650, -1));

        lblConsultarOSPrevCorret.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel1.add(lblConsultarOSPrevCorret, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 630, 30));

        tblConsOSPrevent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CÓD. PROD.", "KM MANUTENÇÃO", "DESCRIÇÃO DO PRODUTO"
            }
        ));
        tblConsOSPrevent.setRowHeight(28);
        scpnlOSPrevent.setViewportView(tblConsOSPrevent);
        if (tblConsOSPrevent.getColumnModel().getColumnCount() > 0) {
            tblConsOSPrevent.getColumnModel().getColumn(2).setPreferredWidth(800);
        }

        jPanel1.add(scpnlOSPrevent, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 1170, 100));

        tblConsOSCorret.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CÓD. PROD.", "DESCRIÇÃO DO PRODUTO"
            }
        ));
        tblConsOSCorret.setRowHeight(28);
        scpnlOSCorret.setViewportView(tblConsOSCorret);
        if (tblConsOSCorret.getColumnModel().getColumnCount() > 0) {
            tblConsOSCorret.getColumnModel().getColumn(1).setPreferredWidth(800);
        }

        jPanel1.add(scpnlOSCorret, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 1170, 100));

        txtCodOSCorretAdd.setBorder(null);
        txtCodOSCorretAdd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtCodOSCorretAdd.setOpaque(false);
        txtCodOSCorretAdd.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtCodOSCorretAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodOSCorretAddKeyReleased(evt);
            }
        });
        jPanel1.add(txtCodOSCorretAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 160, 30));

        txtCodProd.setBorder(null);
        txtCodProd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtCodProd.setOpaque(false);
        txtCodProd.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtCodProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodProdKeyReleased(evt);
            }
        });
        jPanel1.add(txtCodProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, 160, 30));

        btnAdicionarProd.setContentAreaFilled(false);
        btnAdicionarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnAdicionarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, -1, 40));

        btnExcluirProd.setContentAreaFilled(false);
        btnExcluirProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnExcluirProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, 40, 40));

        txtCodOSPrevFin.setBorder(null);
        txtCodOSPrevFin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtCodOSPrevFin.setOpaque(false);
        txtCodOSPrevFin.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtCodOSPrevFin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodOSPrevFinKeyReleased(evt);
            }
        });
        jPanel1.add(txtCodOSPrevFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 690, 160, 20));

        txtCodOSCorretFin.setBorder(null);
        txtCodOSCorretFin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtCodOSCorretFin.setOpaque(false);
        txtCodOSCorretFin.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtCodOSCorretFin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodOSCorretFinKeyReleased(evt);
            }
        });
        jPanel1.add(txtCodOSCorretFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 750, 160, 20));

        txtValorTotPrev.setBorder(null);
        txtValorTotPrev.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtValorTotPrev.setOpaque(false);
        txtValorTotPrev.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtValorTotPrev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorTotPrevKeyReleased(evt);
            }
        });
        jPanel1.add(txtValorTotPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 690, 190, 20));

        txtValorTotCorret.setBorder(null);
        txtValorTotCorret.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtValorTotCorret.setOpaque(false);
        txtValorTotCorret.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtValorTotCorret.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorTotCorretKeyReleased(evt);
            }
        });
        jPanel1.add(txtValorTotCorret, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 750, 190, 20));

        btnSalvarOSFin.setContentAreaFilled(false);
        btnSalvarOSFin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnSalvarOSFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 800, 40, 30));

        btnLimparOSFin.setContentAreaFilled(false);
        btnLimparOSFin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnLimparOSFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 800, 30, 30));

        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 860, 120, 20));

        rdbtn5Prev.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        rdbtn5Prev.setForeground(new java.awt.Color(255, 255, 255));
        rdbtn5Prev.setText("5% REF. SERVIÇO");
        rdbtn5Prev.setToolTipText("");
        jPanel1.add(rdbtn5Prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 690, -1, -1));

        rdbtn10Prev.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        rdbtn10Prev.setForeground(new java.awt.Color(255, 255, 255));
        rdbtn10Prev.setText("10% REF. SERVIÇO");
        jPanel1.add(rdbtn10Prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 690, -1, -1));

        rdbtn20Prev.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        rdbtn20Prev.setForeground(new java.awt.Color(255, 255, 255));
        rdbtn20Prev.setText("20% REF. SERVIÇO");
        jPanel1.add(rdbtn20Prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 690, -1, -1));

        rdbtn5Corret.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        rdbtn5Corret.setForeground(new java.awt.Color(255, 255, 255));
        rdbtn5Corret.setText("5% REF. SERVIÇO");
        jPanel1.add(rdbtn5Corret, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 750, -1, -1));

        rdbtn10Corret.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        rdbtn10Corret.setForeground(new java.awt.Color(255, 255, 255));
        rdbtn10Corret.setText("10% REF. SERVIÇO");
        jPanel1.add(rdbtn10Corret, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 750, -1, -1));

        rdbtn20Corret.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        rdbtn20Corret.setForeground(new java.awt.Color(255, 255, 255));
        rdbtn20Corret.setText("20% REF. SERVIÇO");
        jPanel1.add(rdbtn20Corret, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 750, -1, -1));

        pnlAdicionarProd.setBackground(new java.awt.Color(204, 204, 204));
        pnlAdicionarProd.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlAdicionarProdLayout = new javax.swing.GroupLayout(pnlAdicionarProd);
        pnlAdicionarProd.setLayout(pnlAdicionarProdLayout);
        pnlAdicionarProdLayout.setHorizontalGroup(
            pnlAdicionarProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        pnlAdicionarProdLayout.setVerticalGroup(
            pnlAdicionarProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel1.add(pnlAdicionarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 550, -1, -1));

        lblAdicionarProd.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel1.add(lblAdicionarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, 600, 30));

        pnlFinalizarOS.setBackground(new java.awt.Color(204, 204, 204));
        pnlFinalizarOS.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlFinalizarOSLayout = new javax.swing.GroupLayout(pnlFinalizarOS);
        pnlFinalizarOS.setLayout(pnlFinalizarOSLayout);
        pnlFinalizarOSLayout.setHorizontalGroup(
            pnlFinalizarOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );
        pnlFinalizarOSLayout.setVerticalGroup(
            pnlFinalizarOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel1.add(pnlFinalizarOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 790, 700, -1));

        lblFinalizarOS.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel1.add(lblFinalizarOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 790, 680, 30));

        telaManutencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/TelaManutencao.png"))); // NOI18N
        jPanel1.add(telaManutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlacaManutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaManutKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaManutKeyReleased

    private void txtCodOSCorretAddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodOSCorretAddKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodOSCorretAddKeyReleased

    private void txtCodProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodProdKeyReleased

    private void txtCodOSPrevFinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodOSPrevFinKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodOSPrevFinKeyReleased

    private void txtCodOSCorretFinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodOSCorretFinKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodOSCorretFinKeyReleased

    private void txtValorTotPrevKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorTotPrevKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorTotPrevKeyReleased

    private void txtValorTotCorretKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorTotCorretKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorTotCorretKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(telaManutencao.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaManutencao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarProd;
    private javax.swing.JButton btnConsultarOSManut;
    private javax.swing.JButton btnConsultarPlaca;
    private javax.swing.JButton btnExcluirProd;
    private javax.swing.JButton btnLimparOSFin;
    private javax.swing.JButton btnLimparOSManut;
    private javax.swing.JButton btnLimparPlaca;
    private javax.swing.JButton btnSalvarOSFin;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cboCodOSCorretManut;
    private javax.swing.JComboBox<String> cboCodOSPreventManut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdicionarProd;
    private javax.swing.JLabel lblConsultarOSManut;
    private javax.swing.JLabel lblConsultarOSPrevCorret;
    private javax.swing.JLabel lblFinalizarOS;
    private javax.swing.JPanel pnlAdicionarProd;
    private javax.swing.JPanel pnlConsultarOSManut;
    private javax.swing.JPanel pnlConsultarOSPrevCorret;
    private javax.swing.JPanel pnlFinalizarOS;
    private javax.swing.JRadioButton rdbtn10Corret;
    private javax.swing.JRadioButton rdbtn10Prev;
    private javax.swing.JRadioButton rdbtn20Corret;
    private javax.swing.JRadioButton rdbtn20Prev;
    private javax.swing.JRadioButton rdbtn5Corret;
    private javax.swing.JRadioButton rdbtn5Prev;
    private javax.swing.JScrollPane scpnlOSCorret;
    private javax.swing.JScrollPane scpnlOSPrevent;
    private javax.swing.JTable tblConsOSCorret;
    private javax.swing.JTable tblConsOSPrevent;
    private javax.swing.JLabel telaManutencao;
    private app.bolivia.swing.JCTextField txtCodOSCorretAdd;
    private app.bolivia.swing.JCTextField txtCodOSCorretFin;
    private app.bolivia.swing.JCTextField txtCodOSPrevFin;
    private app.bolivia.swing.JCTextField txtCodProd;
    private app.bolivia.swing.JCTextField txtPlacaManut;
    private app.bolivia.swing.JCTextField txtValorTotCorret;
    private app.bolivia.swing.JCTextField txtValorTotPrev;
    // End of variables declaration//GEN-END:variables
}
