/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author maria
 */
public class telaConsultarProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form telaConsultarProduto
     */
    public telaConsultarProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCadastroItem = new javax.swing.JTable();
        jpnConsDescProd = new javax.swing.JPanel();
        lblConsDescProd = new javax.swing.JLabel();
        txtDescricaoProd = new app.bolivia.swing.JCTextField();
        btnConsultarDescrProd = new javax.swing.JButton();
        btnLimparConsultaProd = new javax.swing.JButton();
        telaConsultarProduto = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Consultar Produto");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tblCadastroItem.setBorder(new javax.swing.border.MatteBorder(null));
        tblCadastroItem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblCadastroItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CÓD.", "DESCRIÇÃO PRODUTO", "MARCA", "MODELO", "COR", "ANO FAB.", "ANO MOD.", "VALOR UNIT."
            }
        ));
        tblCadastroItem.setRowHeight(35);
        tblCadastroItem.setRowMargin(10);
        tblCadastroItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCadastroItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCadastroItem);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 1160, 620));

        jpnConsDescProd.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblConsDescProd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        javax.swing.GroupLayout jpnConsDescProdLayout = new javax.swing.GroupLayout(jpnConsDescProd);
        jpnConsDescProd.setLayout(jpnConsDescProdLayout);
        jpnConsDescProdLayout.setHorizontalGroup(
            jpnConsDescProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnConsDescProdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConsDescProd, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnConsDescProdLayout.setVerticalGroup(
            jpnConsDescProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblConsDescProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel1.add(jpnConsDescProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 680, 40));

        txtDescricaoProd.setBorder(null);
        txtDescricaoProd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtDescricaoProd.setOpaque(false);
        txtDescricaoProd.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtDescricaoProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescricaoProdKeyReleased(evt);
            }
        });
        jPanel1.add(txtDescricaoProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 660, 20));

        btnConsultarDescrProd.setContentAreaFilled(false);
        btnConsultarDescrProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnConsultarDescrProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 100, 40, 40));

        btnLimparConsultaProd.setContentAreaFilled(false);
        btnLimparConsultaProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimparConsultaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparConsultaProdActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimparConsultaProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 40, 40));

        telaConsultarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/TelaConsultarProduto.png"))); // NOI18N
        jPanel1.add(telaConsultarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 890));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCadastroItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCadastroItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCadastroItemMouseClicked

    private void txtDescricaoProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoProdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoProdKeyReleased

    private void btnLimparConsultaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparConsultaProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparConsultaProdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarDescrProd;
    private javax.swing.JButton btnLimparConsultaProd;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnConsDescProd;
    private javax.swing.JLabel lblConsDescProd;
    private javax.swing.JTable tblCadastroItem;
    private javax.swing.JLabel telaConsultarProduto;
    private app.bolivia.swing.JCTextField txtDescricaoProd;
    // End of variables declaration//GEN-END:variables
}
