/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import config.CadastroItem;
import config.Conectar;
import config.PlanoManutencao;
import config.PlanoManutencaoDao;
import config.Plano_ProdutoDao;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
/**
 *
 * @author maria
 */
public class telaConsultaKitManutencao extends javax.swing.JInternalFrame {

    //Criando a conexão com o banco
    Conectar con = new Conectar();

    public telaConsultaKitManutencao() {
        this.con = new Conectar();
        initComponents();
        popularJComboBoxConsultarKit();
        popularJComboBoxConsultarItemKit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboModeloItemKit = new javax.swing.JComboBox<>();
        cboMotorItemKit = new javax.swing.JComboBox<>();
        cboKmManutItemKit = new javax.swing.JComboBox<>();
        cboAnoFabriItemKit = new javax.swing.JComboBox<>();
        cboAnoModItemKit = new javax.swing.JComboBox<>();
        cboMarcaKitVei = new javax.swing.JComboBox<>();
        cboModeloKitVei = new javax.swing.JComboBox<>();
        cboMotorKitVei = new javax.swing.JComboBox<>();
        cboAnoFabriKitVei = new javax.swing.JComboBox<>();
        cboAnoModKitVei = new javax.swing.JComboBox<>();
        btnConsultarItem = new javax.swing.JButton();
        btnLimparItem = new javax.swing.JButton();
        btnConsultarKit = new javax.swing.JButton();
        btnLimparKit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKitporTipoVeiculo = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKitporTipoVeiculo1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblConProdPlan = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblConPlanTpVeic = new javax.swing.JLabel();
        telaConsultaKitManutencao = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(true);
        setTitle("Abraão Lemos LTDA");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboModeloItemKit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboModeloItemKit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cboModeloItemKit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 220, 40));

        cboMotorItemKit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboMotorItemKit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cboMotorItemKit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 210, 40));

        cboKmManutItemKit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboKmManutItemKit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cboKmManutItemKit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 160, 40));

        cboAnoFabriItemKit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboAnoFabriItemKit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cboAnoFabriItemKit, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, 160, 40));

        cboAnoModItemKit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboAnoModItemKit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cboAnoModItemKit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 120, 150, 40));

        cboMarcaKitVei.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboMarcaKitVei.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cboMarcaKitVei, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 220, 40));

        cboModeloKitVei.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboModeloKitVei.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cboModeloKitVei, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 230, 40));

        cboMotorKitVei.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboMotorKitVei.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cboMotorKitVei, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 210, 40));

        cboAnoFabriKitVei.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboAnoFabriKitVei.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cboAnoFabriKitVei, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 540, 150, 40));

        cboAnoModKitVei.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboAnoModKitVei.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cboAnoModKitVei, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 540, 140, 40));

        btnConsultarItem.setContentAreaFilled(false);
        btnConsultarItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarItemActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 120, 40, 40));

        btnLimparItem.setContentAreaFilled(false);
        btnLimparItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimparItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparItemActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimparItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 120, 40, 40));

        btnConsultarKit.setContentAreaFilled(false);
        btnConsultarKit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultarKit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarKitActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarKit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 540, -1, 30));

        btnLimparKit.setContentAreaFilled(false);
        btnLimparKit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimparKit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparKitActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimparKit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 540, 30, 30));

        tblKitporTipoVeiculo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblKitporTipoVeiculo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tblKitporTipoVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CÓD.", "DESCRIÇÃO PRODUTO", "MARCA", "MODELO", "COR", "ANO FAB.", "ANO MOD.", "VALOR UNIT."
            }
        ));
        tblKitporTipoVeiculo.setRowHeight(30);
        jScrollPane1.setViewportView(tblKitporTipoVeiculo);
        if (tblKitporTipoVeiculo.getColumnModel().getColumnCount() > 0) {
            tblKitporTipoVeiculo.getColumnModel().getColumn(0).setPreferredWidth(15);
            tblKitporTipoVeiculo.getColumnModel().getColumn(1).setPreferredWidth(550);
            tblKitporTipoVeiculo.getColumnModel().getColumn(2).setPreferredWidth(40);
            tblKitporTipoVeiculo.getColumnModel().getColumn(3).setPreferredWidth(40);
            tblKitporTipoVeiculo.getColumnModel().getColumn(4).setPreferredWidth(40);
            tblKitporTipoVeiculo.getColumnModel().getColumn(5).setPreferredWidth(15);
            tblKitporTipoVeiculo.getColumnModel().getColumn(6).setPreferredWidth(20);
            tblKitporTipoVeiculo.getColumnModel().getColumn(7).setPreferredWidth(40);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 1180, 200));

        tblKitporTipoVeiculo1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblKitporTipoVeiculo1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tblKitporTipoVeiculo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MARCA", "MODELO", "MOTOR", "ANO MODELO", "ANO FABRICAÇÃO", "KM MANUTENÇÃO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKitporTipoVeiculo1.setRowHeight(30);
        jScrollPane2.setViewportView(tblKitporTipoVeiculo1);
        if (tblKitporTipoVeiculo1.getColumnModel().getColumnCount() > 0) {
            tblKitporTipoVeiculo1.getColumnModel().getColumn(2).setPreferredWidth(150);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 640, 1180, 200));

        lblConProdPlan.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConProdPlan, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblConProdPlan, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 980, 40));

        lblConPlanTpVeic.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConPlanTpVeic, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblConPlanTpVeic, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, 1030, 40));

        telaConsultaKitManutencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/TelaConsultaKitManutencao.png"))); // NOI18N
        jPanel1.add(telaConsultaKitManutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarKitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarKitActionPerformed
        // TODO add your handling code here:

        PlanoManutencaoDao dao = new PlanoManutencaoDao();
        String marca = cboMarcaKitVei.getSelectedItem().toString();
        String modelo = cboModeloKitVei.getSelectedItem().toString();
        String motor = cboMotorKitVei.getSelectedItem().toString();
        Integer anoModelo = (Integer.parseInt(cboAnoModKitVei.getSelectedItem().toString()));
        Integer anoFabricacao = (Integer.parseInt(cboAnoFabriKitVei.getSelectedItem().toString()));

        List<PlanoManutencao> planoEncontrado = dao.consultarPorTipoVeiculo(marca, modelo, motor, anoModelo, anoFabricacao);

        if (planoEncontrado.isEmpty()) {
            lblConPlanTpVeic.setText("Nenhum cadastro encontrado com a descrição fornecida.");
        } else {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("MARCA");
            model.addColumn("MODELO");
            model.addColumn("MOTOR");
            model.addColumn("ANO MODELO");
            model.addColumn("ANO FABRICAÇÃO");
            model.addColumn("KM MANUTENÇÃO");

            for (PlanoManutencao plano : planoEncontrado) {
                model.addRow(new Object[]{
                    plano.getMarca(),
                    plano.getModelo(),
                    plano.getMotor(),
                    plano.getAnoModelo(),
                    plano.getAnoFabricacao(),
                    plano.getKmManutencao(),});
            }
            lblConPlanTpVeic.setText("");
            tblKitporTipoVeiculo1.setModel(model);
        }
    }//GEN-LAST:event_btnConsultarKitActionPerformed

    private void btnLimparKitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparKitActionPerformed
        // TODO add your handling code here:
        lblConPlanTpVeic.setText("");
        DefaultTableModel model = (DefaultTableModel) tblKitporTipoVeiculo1.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnLimparKitActionPerformed

    private void btnConsultarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarItemActionPerformed
        // TODO add your handling code here:

        Plano_ProdutoDao dao = new Plano_ProdutoDao();
        String modelo = cboModeloItemKit.getSelectedItem().toString();
        String motor = cboMotorItemKit.getSelectedItem().toString();
        Integer km = (Integer.parseInt(cboKmManutItemKit.getSelectedItem().toString()));
        Integer anoModelo = (Integer.parseInt(cboAnoModItemKit.getSelectedItem().toString()));
        Integer anoFabricacao = (Integer.parseInt(cboAnoFabriItemKit.getSelectedItem().toString()));

        List<CadastroItem> itensKit = dao.consultarPorItem(modelo, motor, km, anoModelo, anoFabricacao);

        if (itensKit.isEmpty()) {
            lblConProdPlan.setText("Nenhum cadastro encontrado com a descrição fornecida.");
        } else {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("CÓD.");
            model.addColumn("DESCRIÇÃO PRODUTO");
            model.addColumn("MARCA");
            model.addColumn("MODELO");
            model.addColumn("COR");
            model.addColumn("ANO FAB.");
            model.addColumn("ANO MOD.");
            model.addColumn("VALOR UNIT.");

            for (CadastroItem item : itensKit) {
                model.addRow(new Object[]{
                    item.getIdCodigo(),
                    item.getDescricaoItem(),
                    item.getMarca(),
                    item.getModelo(),
                    item.getCor(),
                    item.getAnoFabricacao(),
                    item.getAnoModelo(),
                    item.getValorUnitario()
                });
            }
            lblConProdPlan.setText("");
            tblKitporTipoVeiculo.setModel(model);
            
                tblKitporTipoVeiculo.getColumnModel().getColumn(0).setPreferredWidth(100);
                tblKitporTipoVeiculo.getColumnModel().getColumn(1).setPreferredWidth(800);
                tblKitporTipoVeiculo.getColumnModel().getColumn(2).setPreferredWidth(150);
                tblKitporTipoVeiculo.getColumnModel().getColumn(3).setPreferredWidth(150);
                tblKitporTipoVeiculo.getColumnModel().getColumn(4).setPreferredWidth(100);
                tblKitporTipoVeiculo.getColumnModel().getColumn(5).setPreferredWidth(100);
                tblKitporTipoVeiculo.getColumnModel().getColumn(6).setPreferredWidth(150);
        }

    }//GEN-LAST:event_btnConsultarItemActionPerformed

    private void btnLimparItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparItemActionPerformed
        // TODO add your handling code here:
        lblConProdPlan.setText("");
        DefaultTableModel model = (DefaultTableModel) tblKitporTipoVeiculo.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnLimparItemActionPerformed

    public void popularJComboBoxConsultarKit() {
        Connection cn = con.conexao();
        try {

            String sqlMarca = "SELECT DISTINCT marca FROM veiculo ORDER BY marca ASC";
            Statement stMarca = cn.createStatement();
            ResultSet rsMarca = stMarca.executeQuery(sqlMarca);
            while (rsMarca.next()) {
                cboMarcaKitVei.addItem(rsMarca.getString("marca"));
            }

            String sqlModelo = "SELECT DISTINCT modelo FROM veiculo ORDER BY modelo ASC";
            Statement stModelo = cn.createStatement();
            ResultSet rsModelo = stModelo.executeQuery(sqlModelo);
            while (rsModelo.next()) {
                cboModeloKitVei.addItem(rsModelo.getString("modelo"));
            }

            String sqlMotor = "SELECT DISTINCT motor FROM veiculo ORDER BY motor ASC";
            Statement stMotor = cn.createStatement();
            ResultSet rsMotor = stMotor.executeQuery(sqlMotor);
            while (rsMotor.next()) {
                cboMotorKitVei.addItem(rsMotor.getString("motor"));
            }

            String sqlAnoModelo = "SELECT DISTINCT anoModelo FROM veiculo ORDER BY anoModelo ASC";
            Statement stAnoModelo = cn.createStatement();
            ResultSet rsAnoModelo = stAnoModelo.executeQuery(sqlAnoModelo);
            while (rsAnoModelo.next()) {
                cboAnoModKitVei.addItem(rsAnoModelo.getString("anoModelo"));
            }

            String sqlAnoFabricacao = "SELECT DISTINCT anoFabricacao FROM veiculo ORDER BY anoFabricacao ASC";
            Statement stAnoFabricacao = cn.createStatement();
            ResultSet rsAnoFabricacao = stAnoFabricacao.executeQuery(sqlAnoFabricacao);
            while (rsAnoFabricacao.next()) {
                cboAnoFabriKitVei.addItem(rsAnoFabricacao.getString("anoFabricacao"));
            }
            con.desconectar(cn);
        } catch (SQLException ex) {
            lblConPlanTpVeic.setText("Erro de banco.");
        }

    }

    public void popularJComboBoxConsultarItemKit() {
        Connection cn = con.conexao();
        try {

            String sqlModelo = "SELECT DISTINCT modelo FROM veiculo ORDER BY modelo ASC";
            Statement stModelo = cn.createStatement();
            ResultSet rsModelo = stModelo.executeQuery(sqlModelo);
            while (rsModelo.next()) {
                cboModeloItemKit.addItem(rsModelo.getString("modelo"));
            }

            String sqlMotor = "SELECT DISTINCT motor FROM veiculo ORDER BY motor ASC";
            Statement stMotor = cn.createStatement();
            ResultSet rsMotor = stMotor.executeQuery(sqlMotor);
            while (rsMotor.next()) {
                cboMotorItemKit.addItem(rsMotor.getString("motor"));
            }

            String sqlAnoModelo = "SELECT DISTINCT anoModelo FROM veiculo ORDER BY anoModelo ASC";
            Statement stAnoModelo = cn.createStatement();
            ResultSet rsAnoModelo = stAnoModelo.executeQuery(sqlAnoModelo);
            while (rsAnoModelo.next()) {
                cboAnoModItemKit.addItem(rsAnoModelo.getString("anoModelo"));
            }

            String sqlAnoFabricacao = "SELECT DISTINCT anoFabricacao FROM veiculo ORDER BY anoFabricacao ASC";
            Statement stAnoFabricacao = cn.createStatement();
            ResultSet rsAnoFabricacao = stAnoFabricacao.executeQuery(sqlAnoFabricacao);
            while (rsAnoFabricacao.next()) {
                cboAnoFabriItemKit.addItem(rsAnoFabricacao.getString("anoFabricacao"));
            }

            Integer[] kmManutencao = {10000, 20000, 30000, 40000, 50000, 60000, 70000, 80000, 90000, 100000, 110000,
            120000, 130000, 140000, 150000, 160000, 170000, 180000, 190000, 200000};
            for (Integer km : kmManutencao) {
                cboKmManutItemKit.addItem(km.toString());
            }
            con.desconectar(cn);
        } catch (SQLException ex) {
            lblConProdPlan.setText("Erro de banco.");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaConsultaKitManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaConsultaKitManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaConsultaKitManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaConsultaKitManutencao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaConsultaKitManutencao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarItem;
    private javax.swing.JButton btnConsultarKit;
    private javax.swing.JButton btnLimparItem;
    private javax.swing.JButton btnLimparKit;
    private javax.swing.JComboBox<String> cboAnoFabriItemKit;
    private javax.swing.JComboBox<String> cboAnoFabriKitVei;
    private javax.swing.JComboBox<String> cboAnoModItemKit;
    private javax.swing.JComboBox<String> cboAnoModKitVei;
    private javax.swing.JComboBox<String> cboKmManutItemKit;
    private javax.swing.JComboBox<String> cboMarcaKitVei;
    private javax.swing.JComboBox<String> cboModeloItemKit;
    private javax.swing.JComboBox<String> cboModeloKitVei;
    private javax.swing.JComboBox<String> cboMotorItemKit;
    private javax.swing.JComboBox<String> cboMotorKitVei;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblConPlanTpVeic;
    private javax.swing.JLabel lblConProdPlan;
    private javax.swing.JTable tblKitporTipoVeiculo;
    private javax.swing.JTable tblKitporTipoVeiculo1;
    private javax.swing.JLabel telaConsultaKitManutencao;
    // End of variables declaration//GEN-END:variables
}
